version: '0.1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
  - develop
init:
  - cmd: git config --global core.autocrlf true
configuration:
  - Release
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build ./src/MinimigCli/MinimigCli.csproj -v quiet
artifacts:
  - path: '**/*.nupkg'
skip_commits:
  files:
    - '**/*.md'